workflows:
  react_native_build:
    name: React Native Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        NODE_VERSION: 18
        JAVA_VERSION: 17
        PACKAGE_NAME: "com.pockethelp"
      node: $NODE_VERSION
      java: $JAVA_VERSION
      xcode: latest


      android_signing:
        - codemagic_keystore

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Grant Gradle permissions
        script: |
          cd android
          chmod +x gradlew

      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your.email@example.com
